### PR TITLE
Bg/fix cookbook naming

### PR DESCRIPTION
**Pull request by bhusang**
Don't merge just yet.

### CODE REVIEW

**Comment by callendorph** [comment]
What is the rationale for converting the `-` to `_`?

**Comment by bhusang** [comment]
No particular rationale other than making everything consistent? I thought about using dashes as well. If you feel it would be better with dashes then I can change to that.

**Comment by bhusang** [comment]
This makes the cookbook up to date with jitx and also uses SLM. @callendorph

**Comment by bhusang** [comment]
@callendorph Is this PR ok to get approved? Now that SLM is deployed, it would be good to update the cookbook.

**Pull request merged**
